const EmojiData=[
    {"name": "Smile", "symbol": "😀", "keywords": ["smile", "happy", "joy"]},
    {"name": "Grinning", "symbol": "😁", "keywords": ["grinning", "big smile"]},
    {"name": "Tears of Joy", "symbol": "😂", "keywords": ["tears of joy", "laugh", "funny"]},
    {"name": "Rolling on the Floor Laughing", "symbol": "🤣", "keywords": ["ROFL", "laughing", "hilarious"]},
    {"name": "Slightly Smiling Face", "symbol": "🙂", "keywords": ["slight smile", "content", "pleasant"]},
    {"name": "Upside-Down Face", "symbol": "🙃", "keywords": ["upside down", "silly", "whimsical"]},
    {"name": "Winking Face", "symbol": "😉", "keywords": ["wink", "flirt", "playful"]},
    {"name": "Blushing Face", "symbol": "😊", "keywords": ["blush", "shy", "bashful"]},
    {"name": "Heart Eyes", "symbol": "😍", "keywords": ["heart eyes", "love", "adore"]},
    {"name": "Smiling Face with Halo", "symbol": "😇", "keywords": ["angelic", "innocent", "heavenly"]},
    {"name": "Star-Struck", "symbol": "🤩", "keywords": ["star-struck", "impressed", "awe"]},
    {"name": "Thinking Face", "symbol": "🤔", "keywords": ["thinking", "thoughtful", "pondering"]},
    {"name": "Zipper-Mouth Face", "symbol": "🤐", "keywords": ["zipper mouth", "silent", "secrecy"]},
    {"name": "Face with Raised Eyebrow", "symbol": "🤨", "keywords": ["raised eyebrow", "skeptical", "curious"]},
    {"name": "Neutral Face", "symbol": "😐", "keywords": ["neutral", "indifferent", "expressionless"]},
    {"name": "Expressionless Face", "symbol": "😑", "keywords": ["expressionless", "blank", "emotionless"]},
    {"name": "Face Without Mouth", "symbol": "😶", "keywords": ["face without mouth", "speechless"]},
    {"name": "Smirking Face", "symbol": "😏", "keywords": ["smirk", "smug", "mischievous"]},
    {"name": "Unamused Face", "symbol": "😒", "keywords": ["unamused", "displeased", "unimpressed"]},
    {"name": "Rolling Eyes", "symbol": "🙄", "keywords": ["rolling eyes", "annoyed", "disdain"]},
    {"name": "Grimacing Face", "symbol": "😬", "keywords": ["grimace", "awkward", "uncomfortable"]},
    {"name": "Lying Face", "symbol": "🤥", "keywords": ["lying face", "fib", "untruthful"]},
    {"name": "Relieved Face", "symbol": "😌", "keywords": ["relieved", "satisfied", "content"]},
    {"name": "Pensive Face", "symbol": "😔", "keywords": ["pensive", "thoughtful", "reflective"]},
    {"name": "Sleepy Face", "symbol": "😪", "keywords": ["sleepy", "tired", "exhausted"]},
    {"name": "Drooling Face", "symbol": "🤤", "keywords": ["drooling", "hungry", "craving"]},
    {"name": "Sleeping Face", "symbol": "😴", "keywords": ["sleeping", "zzz", "nap"]},
    {"name": "Relaxed Face", "symbol": "☺️", "keywords": ["relaxed", "serene", "calm"]},
    {"name": "Nerd Face", "symbol": "🤓", "keywords": ["nerd", "geek", "smart"]},
    {"name": "Face with Medical Mask", "symbol": "😷", "keywords": ["medical mask", "health", "sick"]},
    {"name": "Face with Thermometer", "symbol": "🤒", "keywords": ["thermometer", "sick", "unwell"]},
    {"name": "Face with Head-Bandage", "symbol": "🤕", "keywords": ["head bandage", "injured", "hurt"]},
    {"name": "Nauseated Face", "symbol": "🤢", "keywords": ["nauseated", "disgusted", "sick"]},
    {"name": "Face Vomiting", "symbol": "🤮", "keywords": ["vomiting", "throw up", "sick"]},
    {"name": "Sneezing Face", "symbol": "🤧", "keywords": ["sneezing", "cold", "allergy"]},
    {"name": "Hot Face", "symbol": "🥵", "keywords": ["hot", "overheated", "heat"]},
    {"name": "Cold Face", "symbol": "🥶", "keywords": ["cold", "freezing", "chill"]},
    {"name": "Woozy Face", "symbol": "🥴", "keywords": ["woozy", "dizzy", "intoxicated"]},
    {"name": "Dizzy Face", "symbol": "😵", "keywords": ["dizzy", "confused", "unstable"]},
    {"name": "Exploding Head", "symbol": "🤯", "keywords": ["exploding head", "mind blown", "overwhelmed"]},
    {"name": "Cowboy Hat Face", "symbol": "🤠", "keywords": ["cowboy hat", "western", "rodeo"]},
    {"name": "Partying Face", "symbol": "🥳", "keywords": ["partying", "celebration", "fun"]},
    {"name": "Disguised Face", "symbol": "🥸", "keywords": ["disguised", "mask", "hidden"]},
    {"name": "Sunglasses", "symbol": "😎", "keywords": ["sunglasses", "cool", "swag"]},
    {"name": "Smiling Face with Horns", "symbol": "😈", "keywords": ["smiling face with horns", "devilish", "mischievous"]},
    {"name": "Angry Face with Horns", "symbol": "👿", "keywords": ["angry face with horns", "demon", "evil"]},
    {"name": "Clown Face", "symbol": "🤡", "keywords": ["clown face", "circus", "funny"]},
    {"name": "Ghost", "symbol": "👻", "keywords": ["ghost", "spooky", "haunt"]},
    {"name": "Alien", "symbol": "👽", "keywords": ["alien", "extraterrestrial", "UFO"]},
    {"name": "Robot Face", "symbol": "🤖", "keywords": ["robot", "android", "cyborg"]},
    {"name": "Alien Monster", "symbol": "👾", "keywords": ["alien monster", "space invader", "game"]},
    {"name": "Grinning Cat", "symbol": "😺", "keywords": ["grinning cat", "smiling cat", "happy"]},
    {"name": "Smiling Cat with Heart-Eyes", "symbol": "😻", "keywords": ["cat with heart eyes", "love", "adorable"]},
    {"name": "Cat with Wry Smile", "symbol": "😼", "keywords": ["cat with wry smile", "smirk", "mischievous"]},
    {"name": "Kissing Cat", "symbol": "😽", "keywords": ["kissing cat", "smooch", "affectionate"]},
    {"name": "Weary Cat", "symbol": "🙀", "keywords": ["weary cat", "tired", "exhausted"]},
    {"name": "Crying Cat", "symbol": "😿", "keywords": ["crying cat", "sad", "tearful"]},
    {"name": "Pouting Cat", "symbol": "😾", "keywords": ["pouting cat", "angry", "grumpy"]},
    {"name": "Penguin", "symbol": "🐧", "keywords": ["penguin", "cold", "Antarctica"]},
    {"name": "Koala", "symbol": "🐨", "keywords": ["koala", "bear", "cute"]},
    {"name": "Bear", "symbol": "🐻", "keywords": ["bear", "wild", "forest"]},
    {"name": "Panda", "symbol": "🐼", "keywords": ["panda", "bear", "black and white"]},
    {"name": "Fox", "symbol": "🦊", "keywords": ["fox", "animal", "clever"]},
    {"name": "Lion", "symbol": "🦁", "keywords": ["lion", "king", "wild"]},
    {"name": "Tiger", "symbol": "🐯", "keywords": ["tiger", "wildcat", "roar"]},
    {"name": "Leopard", "symbol": "🐆", "keywords": ["leopard", "spots", "wild"]},
    {"name": "Horse", "symbol": "🐴", "keywords": ["horse", "equestrian", "stallion"]},
    {"name": "Unicorn", "symbol": "🦄", "keywords": ["unicorn", "fantasy", "magic"]},
    {"name": "Zebra", "symbol": "🦓", "keywords": ["zebra", "stripes"]},
    {"name": "Zero", "symbol": "0️⃣", "meaning": "The number zero."},
  {"name": "One", "symbol": "1️⃣", "meaning": "The number one."},
  {"name": "Two", "symbol": "2️⃣", "meaning": "The number two."},
  {"name": "Three", "symbol": "3️⃣", "meaning": "The number three."},
  {"name": "Four", "symbol": "4️⃣", "meaning": "The number four."},
  {"name": "Five", "symbol": "5️⃣", "meaning": "The number five."},
  {"name": "Six", "symbol": "6️⃣", "meaning": "The number six."},
  {"name": "Seven", "symbol": "7️⃣", "meaning": "The number seven."},
  {"name": "Eight", "symbol": "8️⃣", "meaning": "The number eight."},
  {"name": "Nine", "symbol": "9️⃣", "meaning": "The number nine."},
  {"name": "Ten", "symbol": "🔟", "meaning": "The number ten."},
  {"name": "Red Heart", "symbol": "❤️", "category": "Love", "keywords": ["heart", "love", "red"]},
  {"name": "Heart Eyes", "symbol": "😍", "category": "Love", "keywords": ["heart", "love", "eyes", "smile"]},
  {"name": "Heart with Arrow", "symbol": "💘", "category": "Love", "keywords": ["heart", "love", "arrow"]},
  {"name": "Two Hearts", "symbol": "💕", "category": "Love", "keywords": ["heart", "love", "two"]},
  {"name": "Sparkling Heart", "symbol": "💖", "category": "Love", "keywords": ["heart", "love", "sparkle"]},
  {"name": "Growing Heart", "symbol": "💗", "category": "Love", "keywords": ["heart", "love", "grow"]},
  {"name": "Heartbeat", "symbol": "💓", "category": "Love", "keywords": ["heart", "love", "beat"]},
  {"name": "Broken Heart", "symbol": "💔", "category": "Love", "keywords": ["heart", "love", "broken"]},
  {"name": "Revolving Hearts", "symbol": "💞", "category": "Love", "keywords": ["heart", "love", "revolving"]},
  {"name": "Heart Decoration", "symbol": "💟", "category": "Love", "keywords": ["heart", "love", "decoration"]},

  ]
  export default EmojiData;
